version: "3.9"
services:
  rtmp:
    build: ./streaming_service
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: blue_streaming_service
#    volumes:
#      - rtmp_data:/app/data

  server:
    build: ./server
    container_name: blue_server
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: "1"
#    volumes:
#      - server_data:/app/data

  chat:
    build: ./chat_service
    container_name: blue_chat_service
    ports:
      - "5555:5555"
    environment:
      PYTHONUNBUFFERED: "1"

  client:
    build: ./client
    ports:
      - "80:3000"
    container_name: blue_client
#    volumes:
#      - client_data:/app/data

#volumes:
#  rtmp_data
#  server_data:
#  client_data:
