"""empty message

Revision ID: 07b2fe6d3279
Revises: 64dfddf6f185
Create Date: 2023-08-17 23:20:04.371414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b2fe6d3279'
down_revision = '64dfddf6f185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
