"""empty message

Revision ID: 53d333af3a4f
Revises: f5b0c52349cb
Create Date: 2023-09-03 21:15:31.216059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d333af3a4f'
down_revision = 'f5b0c52349cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('viewers', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_streams_id'), 'streams', ['id'], unique=False)
    op.create_index(op.f('ix_streams_is_active'), 'streams', ['is_active'], unique=False)
    op.create_index(op.f('ix_streams_viewers'), 'streams', ['viewers'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streams_viewers'), table_name='streams')
    op.drop_index(op.f('ix_streams_is_active'), table_name='streams')
    op.drop_index(op.f('ix_streams_id'), table_name='streams')
    op.drop_column('streams', 'viewers')
    # ### end Alembic commands ###
