"""empty message

Revision ID: 64dfddf6f185
Revises: 
Create Date: 2023-08-14 18:51:40.057955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dfddf6f185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('hashed_token', sa.String(length=80), nullable=False),
    sa.Column('preview', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('email_is_verified', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=80), nullable=False),
    sa.Column('token', sa.String(length=80), nullable=False),
    sa.Column('hashed_token', sa.String(length=80), nullable=False),
    sa.Column('stream_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('streams')
    # ### end Alembic commands ###
