"""empty message

Revision ID: a902f1435fec
Revises: 64dfddf6f185
Create Date: 2023-08-21 14:55:15.543307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a902f1435fec'
down_revision = '64dfddf6f185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('streams', sa.Column('secret_key', sa.String(length=80), nullable=False))
    op.drop_column('streams', 'hashed_token')
    op.drop_column('streams', 'preview')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('preview', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('streams', sa.Column('hashed_token', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('streams', 'secret_key')
    op.drop_column('streams', 'description')
    # ### end Alembic commands ###
