"""empty message

Revision ID: b29a42278867
Revises: a902f1435fec
Create Date: 2023-08-23 16:12:32.534796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29a42278867'
down_revision = 'a902f1435fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('streams', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'streams', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'streams', type_='foreignkey')
    op.drop_column('streams', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
